%searching IAF, TF, & IBF as well as the associated bands
%over corrected frequency spectrum average exported from
%neuroscan; require the freq spectrum avg files be placed 
% in the fspec folder.
%2017-11-20 EC
% adding area measures into the band power computation
%2017-11-10 EC
% tidy up the codes and folder structures
%  *.avg of frequency spectrum in fspec/data folder
%  plots of the markers in fspec/figures 
%  scripts in ADHDeeg main folder
%2017-11-07 created by Erik Chang


%%



droot='fspec/data';
fns = dir('fspec/data/*.avg');
%define channel name
chanstr = 'FP1';


close all;
for f = 1:length(fns)
%for f=1:1
    fn = sprintf('%s/%s',droot,fns(f).name);
    res = findmarkers_fspec(fn, ...
        chanstr,false,'fspec/figures');
    %pfolder = 'fspec/figures' %for debugging
    %findmarkers_fspec; %for debugging
    
    %for unpacking the struct res
    save('temp.mat','-struct','res')
    load('temp.mat');
    if f==1
        tab=table(cTF,cIAF,cIBF,...
            cTB,cAB,cBB,area_cTB,sm_area_cTB,...
            area_cAB,sm_area_cAB,...
            area_cBB,sm_area_cBB,...
            avg_cTB,sm_avg_cTB,...
            avg_cAB,sm_avg_cAB,...
            avg_cBB,sm_avg_cBB);
    else
        tab=[tab; ...
            table(cTF,cIAF,cIBF,...
        cTB,cAB,cBB,area_cTB,sm_area_cTB,...
            area_cAB,sm_area_cAB,...
            area_cBB,sm_area_cBB,...
            avg_cTB,sm_avg_cTB,...
            avg_cAB,sm_avg_cAB,...
            avg_cBB,sm_avg_cBB)];
    end
end

tab.Properties.VariableNames=...
    {'TF','IAF','IBF','TB','AB','BB',...
    'area_TB','sm_area_TB',...
            'area_AB','sm_area_AB',...
            'area_BB','sm_area_BB',...
            'avg_TB','sm_avg_TB',...
            'avg_AB','sm_avg_AB',...
            'avg_BB','sm_avg_BB'};
tab.Properties.RowNames={fns.name}';

tab.Properties.Description = ['1/f corrected '...
    'by fitting least square linear function through '...
    '2-5 & 30-40 Hz'];
writetable(tab, 'fspec/summary.fspec.txt',...
    'Delimiter',',','WriteRowNames',true);

